apiVersion: v1
kind: Secret
metadata:
  name: stats-monitor-sa-token
  namespace: monitoring
  annotations:
    kubernetes.io/service-account.name: "stats-monitor-sa"
type: kubernetes.io/service-account-token