apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: data
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: busybox
          command: ['sh', '-c', 'echo "init data" > /var/lib/mysql/data.db && sleep 3600']