apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: prod
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: busybox
          command: ['sh', '-c', 'while true; do sleep 3600; done']