apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: data
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: busybox
          command: ['sh', '-c', 'while true; do sleep 3600; done']