apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-unprivileged-deployment
  namespace: confidential
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginxinc/nginx-unprivileged:alpine3.23-perl
          ports:
            containerPort: 8080
