apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb
  labels:
    app: couchdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchdb
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      containers:
        - name: couchdb
          image: couchdb:3.3.3
          imagePullPolicy: Always
          env:
            - name: POD_IP
              valueFrom:
                fieldPath: status.podIP
            - name: ERL_FLAGS
              value: "-name couchdb@$(POD_IP) -setcookie 9dsafjasjf390dkljfaldjfkfd233"
            - name: COUCHDB_USER
              value: "1pro"
            - name: COUCHDB_PASSWORD
              value: "admin"
          ports:
            - name: couchdb
              containerPort: 5984
            - name: epmd
              containerPort: 4369
            - containerPort: 9100
          securityContext:
            runAsUser: 65535
            readOnlyRootFilesystem: false
            privileged: false
            capabilities:
              drop:
                - "all"
              add:
                - NET_BIND_SERVICE
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "256m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /healthCheck
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          volumeMounts:
            - name: database-storage
              mountPath: /var/lib/database
      volumes:
        - name: database-storage
          emptyDir: {}