apiVersion: apps/v1
kind: Deployment
metadata:
  name: clever-cactus
  namespace: clever-cactus
  labels:
    app: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: httpd:2.4-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
          volumeMounts:
            - name: config
              mountPath: /usr/local/apache2/conf/httpd.conf
              subPath: httpd.conf
            - name: tls-certificate
              mountPath: /usr/local/apache2/conf/server.crt
              subPath: tls.crt
            - name: tls-key
              mountPath: /usr/local/apache2/conf/server.key
              subPath: tls.key
      initContainers:
        - name: config
          image: httpd:2.4-alpine
          imagePullPolicy: IfNotPresent
          command:
            - /bin/ash
            - -c
          args:
            - |
              sed -e 's/#\(Include .*httpd-ssl.conf\)/\1/' \
                  -e 's/#\(LoadModule .*mod_ssl.so\)/\1/' \
                  -e 's/#\(LoadModule .*mod_socache_shmcb.so\)/\1/' \
                  /usr/local/apache2/conf/httpd.conf > /config/httpd.conf
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          emptyDir: {}
        - name: tls-certificate
          secret:
            secretName: clever-cactus
            defaultMode: 420
        - name: tls-key
          secret:
            secretName: clever-cactus
            defaultMode: 420