apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: mtls
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: 1pro/exam
          ports:
            - containerPort: 8080